example = str(input())
print("Первый символ: " + example[0])
print("Последний символ: " + example[-1])
print("Вторая половина строки: " + example[len(example) // 2:])
print("Слово наоборот: " + example[::-1])
print("Каждый второй символ строки: " + example[1::2])
